config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get '/about', to: 'home#about'

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'signup' }

  resources :posts
  resources :users do
    member do
      get :all_posts, path: '/all-posts'
    end
  end

  resources :comments, except: [:index]
  resources :contact, only: [:index, :new, :create]

end

app/models/user.rb
class User
  include Mongoid::Document

  field :username, type: String
  field :about, type: String

  validates :username, :about, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :posts, autosave: true, dependent: :destroy
  has_many :comments, autosave: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  # field :sign_in_count,      type: Integer, default: 0
  # field :current_sign_in_at, type: Time
  # field :last_sign_in_at,    type: Time
  # field :current_sign_in_ip, type: String
  # field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %w[edit update destroy show all_posts]

  def index
    @users = User.all
  end

  def show
    @posts = @user.posts.limit(3).order(created_at: :desc)
    @comments = @user.comments
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User profile has been updated!' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'User account has been deleted. Bye!' }
      format.json { head :no_content }
    end
  end

  def all_posts
    @posts = @user.posts.page(params[:page]).per(10).order(created_at: :desc)
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:comment).permit(:username, :email, :password, :password_confirmation)
    end
end

app/views/users/all_posts.html.erb
<% provide(:title, 'All Posts By ' + @user.username) %>

<h1 class="title is-1">
  All Blog Posts By <%= @user.username %>
</h1>
<hr>

<%= render 'shared/post_index' %>

app/views/users/index.html.erb
<% provide(:title, 'All Users') %>

<h1 class="title is-1" style="padding-bottom:12px;">User Index</h1>
<hr>

<% @users.each do |user| %>
  <ul>
    <div class="columns is-vcentered">
      <div class="column">
        <%= link_to user do %>
          <%= user.username %>
        <% end %>
      </div>
      <div class="column column is-offset-4 is-2">
        <%= link_to 'View Profile!', user_path(user),
                class: 'button is-link is-fullwidth' %>
      </div>
    </div>
  </ul>
  <hr>
<% end %>

app/views/users/show.html.erb
<% provide(:title, @user.username) %>

<% if @user === current_user %>
  <div class="columns">
    <div class="column">
      <%= link_to 'Write New Blog Post', new_post_path, class: 'button is-success is-fullwidth' %>
    </div>
    <div class="column">
      <%= link_to 'Edit User Profile', edit_user_registration_url(@user), class: 'button is-warning is-fullwidth' %>
    </div>
    <div class="column">
      <%= link_to 'Delete User Profile', @user, method: :delete, data: { confirm: 'Are you sure?' }, class: 'button is-danger is-fullwidth' %>
    </div>
  </div>
<% end %>

<h1 class="title is-1">
  <%= @user.username %>
</h1>
<p class="is-size-5">
  A Quote From <%= @user.username %>: <span class="is-italic has-text-grey">"<%= @user.about %>"</span>
</p>
<hr>

<div class="columns is-vcentered">
  <div class="column">
    <h5 class="title is-5">
      <%= @user.username.pluralize %> three most recent Blog Posts:
    </h5>
  </div>
  <div class="column">
    <h5 class="title is-5 is-pulled-right">
      <%= link_to all_posts_user_path do %>
        All Posts By <%= @user.username %>
      <% end %>
    </h5>
  </div>
</div>
<hr>
<%= render 'shared/post_index' %>