config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get '/about', to: 'home#about'

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'signup' }

  resources :posts
  resources :users do
    member do
      get :all_posts, path: '/all-posts'
    end
  end

  resources :comments, except: [:index]
  resources :contact, only: [:index, :new, :create]

end

app/views/layouts/partials/_footer.html.erb
<footer class="footer">
  <div class="content has-text-centered">
    <p class="has-text-centered">
      &copy; Site built, maintained and desgined by Red Hendery.
    </p>
  </div>
</footer>

app/views/layouts/partials/_navbar.html.erb
<nav class="navbar is-primary">
  <div class="container">
    <div class="navbar-brand">

      <%= link_to 'Blogus Latinus', root_path, class: 'navbar-item' %>

      <span class="navbar-burger burger" data-target="navMenu">
        <span></span>
        <span></span>
        <span></span>
      </span>
    </div>

    <div id="navMenu" class="navbar-menu">
      <div class="navbar-end">
        <% if user_signed_in? %>
          <%= link_to 'About', about_path, class: 'navbar-item' %>
          <%= link_to 'Contact', contact_index_path, class: 'navbar-item' %>
          <%= link_to 'Users', users_path, class: 'navbar-item' %>
          <%= link_to 'Posts', posts_path, class: 'navbar-item' %>
          <%= link_to 'My Profile', user_path(current_user), class: 'navbar-item' %>
          <%= link_to 'Log Out', destroy_user_session_url, method: :delete, class: 'navbar-item' %>
          <%= link_to 'Check Out The Code Here', 'https://github.com/redhendery/blogus-latinus', target: 'blank', class: 'navbar-item' %>
        <% else %>
          <%= link_to 'About', about_path, class: 'navbar-item' %>
          <%= link_to 'Contact', contact_index_path, class: 'navbar-item' %>
          <%= link_to 'Users', users_path, class: 'navbar-item' %>
          <%= link_to 'Posts', posts_path, class: 'navbar-item' %>
          <%= link_to 'Sign Up', new_user_registration_url, class: 'navbar-item' %>
          <%= link_to 'Log In', new_user_session_url, class: 'navbar-item' %>
          <%= link_to 'Check Out The Code Here', 'https://github.com/redhendery/blogus-latinus', target: 'blank', class: 'navbar-item' %>
        <% end %>
      </div>
    </div>
  </div>
</nav>

<script type="text/javascript">
  (function() {
    var burger = document.querySelector('.burger');
    var nav = document.querySelector('#'+burger.dataset.target);
    burger.addEventListener('click', function(){
      burger.classList.toggle('is-active');
      nav.classList.toggle('is-active');
    });
  })();
</script>

app/views/layouts/partials/_rails_default.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1">

<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>